// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomePageDocumentDataSlicesSlice =
  | HeroSlice
  | InteractiveViolinsAnimationSlice
  | CarouselSlice
  | ContactSlice
  | VynilSlice;

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Content for Repertoire Songs documents
 */
interface RepertoireSongsDocumentData {
  /**
   * Album Image field in *Repertoire Songs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire_songs.album_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  album_image: prismic.ImageField<never>;

  /**
   * Song Artist and Name field in *Repertoire Songs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: repertoire_songs.song_artist_and_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_artist_and_name: prismic.KeyTextField;
}

/**
 * Repertoire Songs document from Prismic
 *
 * - **API ID**: `repertoire_songs`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RepertoireSongsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<RepertoireSongsDocumentData>,
    "repertoire_songs",
    Lang
  >;

export type AllDocumentTypes = HomePageDocument | RepertoireSongsDocument;

/**
 * Item in *Carousel → Default → Primary → Repertoire Songs*
 */
export interface CarouselSliceDefaultPrimaryRepertoireSongsItem {
  /**
   * Album Image field in *Carousel → Default → Primary → Repertoire Songs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.repertoire_songs[].album_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  album_image: prismic.ImageField<never>;

  /**
   * Song Artist and Name field in *Carousel → Default → Primary → Repertoire Songs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.repertoire_songs[].song_artist_and_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  song_artist_and_name: prismic.KeyTextField;
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Repertoire Songs field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.repertoire_songs[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repertoire_songs: prismic.GroupField<
    Simplify<CarouselSliceDefaultPrimaryRepertoireSongsItem>
  >;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Clifton String Quartet
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *InteractiveViolinsAnimation → Default → Primary*
 */
export interface InteractiveViolinsAnimationSliceDefaultPrimary {
  /**
   * Background Image field in *InteractiveViolinsAnimation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: interactive_violins_animation.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for InteractiveViolinsAnimation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InteractiveViolinsAnimationSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<InteractiveViolinsAnimationSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *InteractiveViolinsAnimation*
 */
type InteractiveViolinsAnimationSliceVariation =
  InteractiveViolinsAnimationSliceDefault;

/**
 * InteractiveViolinsAnimation Shared Slice
 *
 * - **API ID**: `interactive_violins_animation`
 * - **Description**: InteractiveViolinsAnimation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InteractiveViolinsAnimationSlice = prismic.SharedSlice<
  "interactive_violins_animation",
  InteractiveViolinsAnimationSliceVariation
>;

/**
 * Default variation for Vinyl Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VynilSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Vinyl*
 */
type VynilSliceVariation = VynilSliceDefault;

/**
 * Vinyl Shared Slice
 *
 * - **API ID**: `vynil`
 * - **Description**: Vynil
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VynilSlice = prismic.SharedSlice<"vynil", VynilSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      RepertoireSongsDocument,
      RepertoireSongsDocumentData,
      AllDocumentTypes,
      CarouselSlice,
      CarouselSliceDefaultPrimaryRepertoireSongsItem,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      ContactSlice,
      ContactSliceVariation,
      ContactSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      InteractiveViolinsAnimationSlice,
      InteractiveViolinsAnimationSliceDefaultPrimary,
      InteractiveViolinsAnimationSliceVariation,
      InteractiveViolinsAnimationSliceDefault,
      VynilSlice,
      VynilSliceVariation,
      VynilSliceDefault,
    };
  }
}
