// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  carousel: dynamic(() => import("./Carousel")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  interactive_violins_animation: dynamic(
    () => import("./InteractiveViolinsAnimation"),
  ),
  vynil: dynamic(() => import("./Vinyl")),
};
